[workspace]
members = [
    "tools",

    # Common.
    "common",
    "common/api",

    # Random beacon.
    "beacon/base",
    "beacon/dummy",

    # Random beacon.
    "beacon/base",
    "beacon/dummy",

    # Consensus interface.
    "consensus/base",
    "consensus/dummy",

    # Storage interface.
    "storage/base",
    "storage/dummy",

    # Enclave loader (+ attestation).
    "enclave/common",
    "enclave/untrusted",
    "enclave/trusted",

    # RPC.
    "rpc/common",
    "rpc/client",
    "rpc/untrusted",
    "rpc/trusted",
    "rpc/edl",

    # Database.
    "db/untrusted",
    "db/trusted",
    "db/edl",

    # Contract invocation.
    "contract/common",
    "contract/client",
    "contract/untrusted",
    "contract/trusted",
    "contract/edl",

    # Core.
    "core/common",
    "core/untrusted",
    "core/trusted",
    "core/edl",

    # Compute node.
    "compute/api",
    "compute",

    # Consensus node (deprecated).
    "consensus/api",
    "consensus",

    # Core contracts.
    "contracts/key-manager",
    "contracts/token",

    # Clients.
    "clients/token",

    # Registry.
    "registry/api",
    "registry/base",
    "registry/dummy",
]
